repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0 # pin → latest stable
    hooks:
      - id: black
        language_version: python3.13.3
        args: ["--line-length=88"]
  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-bugbear"]
        args: ["--max-line-length=88"]
